spring.application.name=payment-service
server.port=8083

resilience4j.circuitbreaker.instances.sampleService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.sampleService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.sampleService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.sampleService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.sampleService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.sampleService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.sampleService.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.sampleService.recordExceptions=java.lang.RuntimeException